### ISSUE TITLE
Add CSS for overall web pages (general project "style")

### ISSUE THREAD

**Issue by grayson073** [MoneyWithWings/Bootcamp1ProjectWeek#34]

**Comment by rbtprograms** [comment]
Does anyone have any interest in trying to use some modern web design frameworks (Bootstrap, Material Design, etc.) to style our website? The basics are simple and can make web apps look professionally done.

**Comment by Rehmsy** [comment]
That sounds good to me. But could that interfere with the mock web page coding, since that's part of another page and not its own entity?

**Comment by rbtprograms** [comment]
almost closable! just some final touches
